debug: false
ingress:
  enabled: true
  includeDefaultExtraAnnotations: true
  ingressClassName: nginx
  extraAnnotations:
    "kubernetes.io/tls-acme": "true"
    "cert-manager.io/cluster-issuer": "example.com-letsencrypt-issuer"
  #    "nginx.ingress.kubernetes.io/server-snippet": |-
  #      deny 10.14.0.1/32;
  #      allow 10.0.0.0/8;
  #      deny all;
  tls:
    # options: rancher, letsEncrypt, secret
    source: secret

replicas: 1
tls: ingress
