apiVersion: v1
kind: Service
metadata:
  name: metatube
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metatube-svc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    my-app: emby-plugin-metatube
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metatube
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-example
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    my-app: emby-plugin-metatube
  name: metatube
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      my-app: emby-plugin-metatube
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        my-app: emby-plugin-metatube
    spec:
      affinity: {}
      containers:
      - env:
        - name: DSN
          value: /config/metatube.db
        image: metatube/metatube-server:dev
        imagePullPolicy: IfNotPresent
        name: metatube
        ports:
        - containerPort: 8080
          name: metatube-svc
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: vol-metatube
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol-metatube
        persistentVolumeClaim:
          claimName: metatube