global:
  nameOverride: handbrake

defaultPodOptions: {}
  
controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      main:
        order: 1
        image:
          repository: esphome/esphome
          tag: stable
          pullPolicy: IfNotPresent
        env:
          TZ: Asia/Shanghai
          # ESPHOME_DASHBOARD_USE_PING: true
          # ESPHOME_DASHBOARD_RELATIVE_URL: "/"
          # ESPHOME_QUICKWIZARD:
          # ESPHOME_IS_HASSIO:
          # DISABLE_HA_AUTHENTICATION:
          # USERNAME:
          # PASSWORD:
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

service:
  main:
    enabled: true
    primary: true
    controller: main
    ports:
      http:
        enabled: true
        port: 6052

ingress:
  main:
    enabled: true
    primary: true
    annotations:
      helm.sh/resource-policy: keep
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: example.com-letsencrypt-issuer
      nginx.ingress.kubernetes.io/server-snippet: |-
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;
    className: "nginx"
    hosts:
      - host: esp.example.com
        paths:
        - path: /
          pathType: Prefix
          service:
            name: esphome
            port: 6052
    tls:
    - hosts:
      - esp.example.com
      secretName: esp.example.com-tls      

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: sc-example
    accessMode: ReadWriteOnce
    size: 10Gi
    retain: true
    globalMounts: []
    advancedMounts:
      main:  # the controller with the "main"
        main:  # the container with the "main"
        - path: /config
          readOnly: false
          