global:
  nameOverride: alist

defaultPodOptions: {}
  
controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      main:
        order: 1
        image:
          repository: xhofe/alist
          tag: latest
          pullPolicy: IfNotPresent
        env:
          PUID: 0
          PGID: 0
          UMASK: 022
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

service:
  main:
    enabled: true
    primary: true
    controller: main
    ports:
      http:
        enabled: true
        port: 5244

ingress:
  main:
    enabled: true
    primary: true
    annotations:
      helm.sh/resource-policy: keep
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: example.com-letsencrypt-issuer
    className: "nginx"
    hosts:
      - host: li.example.com
        paths:
        - path: /
          pathType: Prefix
          service:
            name: alist
            port: 5800
    tls:
    - hosts:
      - li.example.com
      secretName: li.example.com-tls      

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: local-zfs-sc
    accessMode: ReadWriteOnce
    size: 10Gi
    retain: true
    globalMounts: []
    advancedMounts:
      main:  # the controller with the "main"
        main:  # the container with the "main"
        - path: /opt/alist/data
          readOnly: false
          