global:
  nameOverride: losslesscut

defaultPodOptions: {}
  
controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      main:
        order: 1
        image:
          repository: jutze/losslesscut
          tag: 3.59.1
          pullPolicy: IfNotPresent
        env:
          TZ: Asia/Shanghai
          USER_ID: 0
          GROUP_ID: 0
          SUP_GROUP_IDS: "33,1000"
          LANG: zh_CN.UTF-8
          CONTAINER_DEBUG: 0
          DISPLAY_WIDTH: 1920
          DISPLAY_HEIGHT: 1080
          DARK_MODE: 0
          APP_NICENESS: 10
          VNC_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: password
                key: vnc-password
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
        resources:
          limits:
            cpu: '6'

service:
  main:
    enabled: true
    primary: true
    controller: main
    ports:
      http:
        enabled: true
        port: 5800

ingress:
  main:
    enabled: true
    primary: true
    annotations:
      helm.sh/resource-policy: keep
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: example.com-letsencrypt-issuer
    ingressClassName: "nginx"
    hosts:
      - host: lc.example.com
        paths:
        - path: /
          pathType: Prefix
          service:
            name: losslesscut
            port: 5800
    tls:
    - hosts:
      - lc.example.com
      secretName: lc.example.com-tls      

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: local-zfs-sc
    accessMode: ReadWriteOnce
    size: 10Gi
    retain: true
    globalMounts: []
    advancedMounts:
      main:  # the controller with the "main"
        main:  # the container with the "main"
        - path: /config
          readOnly: false

  # media:
  #   enabled: true
  #   type: hostPath
  #   hostPath: /mnt/media
  #   advancedMounts:
  #     main:
  #       main:
  #       - path: /storage
  #         readOnly: false
  #       - path: /mnt/media
  #         readOnly: false