global:
  defaultStorageClass: sc-example
  postgresql:
    auth:
      username: admin
      database: gitlabhq_production

clusterDomain: "cluster.local"
# 数据库HA和复制模式，使用几年下来效果并不理想，对于大部分需求来说，单节点足够了
architecture: standalone

primary:
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 8
      memory: 16Gi
  service:
    type: ClusterIP
  persistence:
    size: 50Gi

image:
  registry: docker.io
  repository: bitnami/postgresql
