global:
  defaultStorageClass: "mass"

mode: standalone

persistence:
  enabled: true
  annotations:
    helm.sh/resource-policy: keep
  size: 2000Gi

resources:
  requests:
    cpu: 1
    memory: 512Mi
  limits:
    cpu: 4
    memory: 8Gi

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: s3.example.com
  annotations:
    helm.sh/resource-policy: keep
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: example.com-letsencrypt-issuer
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
  extraTls:
    - hosts:
        - s3.example.com
        - "*.s3.example.com"
      secretName: s3.example.com-tls

apiIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: api.s3.example.com
  annotations:
    helm.sh/resource-policy: keep
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: example.com-letsencrypt-issuer
  extraTls:
    - hosts:
        - s3.example.com
        - "*.s3.example.com"
      secretName: s3.example.com-tls
