global:
  defaultStorageClass: "mass"

mode: standalone

persistence:
  enabled: true
  size: 2000Gi

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: s3.example.com
  annotations:
    helm.sh/resource-policy: keep
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: example.com-letsencrypt-issuer
  tls: true
  extraTls:
    - hosts:
        - "*.s3.example.com"
      secretName: s3.example.com-tls

apiIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: api.s3.example.com
  annotations:
    helm.sh/resource-policy: keep
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: example.com-letsencrypt-issuer
  tls: true
  extraTls:
    - hosts:
        - "*.s3.example.com"
      secretName: s3.example.com-tls
