apiVersion: v2
appVersion: 2.6.8
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: ~2
description: Community developed LDAP software
home: https://www.openldap.org
icon: https://raw.githubusercontent.com/jp-gouin/helm-openldap/master/logo.png
keywords:
- ldap
- openldap
- iam-stack
- high availability
maintainers:
- email: jp-gouin@hotmail.fr
  name: Jean-Philippe Gouin
name: openldap-stack-ha
sources:
- https://github.com/jp-gouin/helm-openldap
version: 4.2.5
