global:
  fullnameOverride: rustdesk

defaultPodOptions:
  hostAliases:
    - ip: "127.0.0.1"
      hostnames:
        - "rustdesk.com"

controllers:
  main:
    enabled: true
    forceRename: rustdesk
    type: deployment
    replicas: 1
    containers:
      hbbs:
        image:
          repository: jutze/remote-desktop
          tag: 1.1.15
          pullPolicy: IfNotPresent
        command: ["hbbs"]
        env:
          TZ: ${TIMEZONE}
          RUST_LOG: "info"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2
            memory: 2048Mi
      hbbr:
        image:
          repository: jutze/remote-desktop
          tag: 1.1.15
          pullPolicy: IfNotPresent
        command: ["hbbr"]
        env:
          TZ: ${TIMEZONE}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 4
            memory: 2048Mi
      license-server:
        image:
          repository: jutze/remote-desktop
          tag: 1.1.15
          pullPolicy: IfNotPresent
        command: ["license-server"]
        env:
          TZ: ${TIMEZONE}
          LICENSE_TYPE: "2" # 1: basic 2: advanced 3: custom
          LICENSE_MAX_PEERS: "999999999"
          LICENSE_MAX_USERS: "999999999"
          LICENSE_MAX_CONNS: "999999999"
          LICENSE_EXPIRY_SECS: "3153600000"
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi

service:
  rustdesk:
    enabled: true
    forceRename: rustdesk
    controller: main
    type: LoadBalancer
    loadBalancerIP: 10.33.0.6
    externalTrafficPolicy: Local
    externalIPs:
      - 10.33.0.13 # 内网域名劫持到本地lb时和ingress共享ip，这样可以同时访问443和21114-21119端口
    ports:
      nat-test:
        enabled: true
        port: 21115
        protocol: TCP
      id-register-tcp:
        enabled: true
        primary: true
        port: 21116
        protocol: TCP
      id-register-udp:
        enabled: true
        port: 21116
        protocol: UDP
      relay:
        enabled: true
        port: 21117
        protocol: TCP
      # ingress
      web-console:
        enabled: true
        port: 21114
        protocol: TCP
      web-client:
        enabled: true
        port: 21118
        protocol: TCP
      relay-web-client:
        enabled: true
        port: 21119
        protocol: TCP

ingress:
  rustdesk:
    enabled: true
    annotations:
      helm.sh/resource-policy: keep
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: ${DOMAIN}-letsencrypt-issuer
      nginx.ingress.kubernetes.io/app-root: /static/web/index.html
      nginx.ingress.kubernetes.io/configuration-snippet: |-
        if ($uri = /static/index.html) {
             return 403;
        }
    className: "nginx"
    hosts:
      - host: rd.${DOMAIN}
        paths:
          - path: /
            pathType: Prefix
            service:
              name: rustdesk
              port: 21114
          - path: /ws/id
            pathType: Prefix
            service:
              name: rustdesk
              port: 21118
          - path: /ws/relay
            pathType: Prefix
            service:
              name: rustdesk
              port: 21119
    tls:
      - hosts:
          - rd.${DOMAIN}
          - rd-mgr.${DOMAIN}
        secretName: rustdesk-tls
  mgr:
    enabled: true
    annotations:
      helm.sh/resource-policy: keep
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: ${DOMAIN}-letsencrypt-issuer
      nginx.ingress.kubernetes.io/app-root: /static/index.html
      nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
    className: "nginx"
    hosts:
      - host: rd-mgr.${DOMAIN}
        paths:
          - path: /
            pathType: Prefix
            service:
              name: rustdesk
              port: 21114
    tls:
      - hosts:
          - rd.${DOMAIN}
          - rd-mgr.${DOMAIN}
        secretName: rustdesk-tls

persistence:
  data:
    enabled: true
    forceRename: rustdesk-data
    type: persistentVolumeClaim
    storageClass: ${DEFAULT_STORAGE_CLASS}
    accessMode: ReadWriteOnce
    size: 10Gi
    retain: true
    globalMounts:
      - path: /root
        readOnly: false
