apiVersion: v1
data:
  root: |-
    */3 * * * * php -f /var/www/html/occ preview:pre-generate
    */5 * * * * php -f /var/www/html/cron.php
kind: ConfigMap
metadata:
  name: busybox-cron
---
apiVersion: v1
data:
  nginx.conf: |-
    user  root;
    worker_processes  8;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        set_real_ip_from 10.0.0.0/8;
        set_real_ip_from 192.168.0.0/16;
        set_real_ip_from 172.16.0.0/12;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;

        include /etc/nginx/conf.d/*.conf;
    }

kind: ConfigMap
metadata:
  name: nginx-root-config
