global:
  defaultStorageClass: sc-example
  security:
    allowInsecureImages: true

clusterDomain: cluster.local
architecture: standalone

image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: 8.2.1-debian-12-r0

master:
  persistence:
    size: 10Gi
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 4Gi
