global:
  defaultStorageClass: sc-example
  postgresql:
    auth:
      username: nextcloud
      database: nextcloud

clusterDomain: "cluster.local"
# 数据库HA和复制模式，使用几年下来效果并不理想，对于大部分需求来说，单节点足够了
architecture: standalone

primary:
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 8
      memory: 16Gi
  service:
    type: LoadBalancer
  persistence:
    size: 50Gi

image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.6.0-debian-12-r4
