global:
  nameOverride: mgr-auth

controllers:
  main:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      main:
        image:
          repository: ${MGR_AUTH_IMAGE_REPOSITORY}
          tag: ${MGR_AUTH_IMAGE_TAG}
          pullPolicy: IfNotPresent
        env:
          LOG_LEVEL: warn
          NODE_ENV: production
          DATA_DIR: /opt/auth-mgr/
          PUBLIC_ORIGIN: https://mgr.auth.${DOMAIN}
          TRUSTED_PROXY_CIDRS: ${CLUSTER_CIDR}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 512Mi

service:
  main:
    enabled: true
    primary: true
    controller: main
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 80
        targetPort: 3004

persistence:
  data:
    enabled: true
    forceRename: mgr-auth-data
    type: persistentVolumeClaim
    storageClass: ${DEFAULT_STORAGE_CLASS}
    accessMode: ReadWriteOnce
    size: 20Gi
    retain: true
    globalMounts:
      - path: /opt/auth-mgr/
        readOnly: false

ingress:
  main:
    enabled: true
    annotations:
      helm.sh/resource-policy: keep
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: ${DOMAIN}-letsencrypt-issuer
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    className: "nginx"
    hosts:
      - host: mgr.auth.${DOMAIN}
        paths:
          - path: /
            pathType: Prefix
            service:
              name: mgr-auth
              port: 80
    tls:
      - hosts:
          - auth.${DOMAIN}
          - "*.auth.${DOMAIN}"
        secretName: auth.${DOMAIN}-tls
